# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "sass", ">= 3.2.9"
gem "compass", ">= 0.12.2"
gem "compass-h5bp", ">= 0.1.1"